SET FOREIGN_KEY_CHECKS = 0;
DELETE FROM answer;
DELETE FROM response;
DELETE FROM config;
DELETE FROM permission;
DELETE FROM `option`;
DELETE FROM question;
DELETE FROM paper;
DELETE FROM project_school;
DELETE FROM project_user;
DELETE FROM project;
DELETE FROM user;
DELETE FROM school;
DELETE FROM tool;
SET FOREIGN_KEY_CHECKS = 1;
SELECT 'all cleared' AS status;
